// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: catalog-product.proto

package io.dmcapps.proto.catalog;

public interface ProductResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:io.dmcapps.proto.catalog.ProductResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .io.dmcapps.proto.catalog.Product products = 1;</code>
   */
  java.util.List<io.dmcapps.proto.catalog.Product> 
      getProductsList();
  /**
   * <code>repeated .io.dmcapps.proto.catalog.Product products = 1;</code>
   */
  io.dmcapps.proto.catalog.Product getProducts(int index);
  /**
   * <code>repeated .io.dmcapps.proto.catalog.Product products = 1;</code>
   */
  int getProductsCount();
  /**
   * <code>repeated .io.dmcapps.proto.catalog.Product products = 1;</code>
   */
  java.util.List<? extends io.dmcapps.proto.catalog.ProductOrBuilder> 
      getProductsOrBuilderList();
  /**
   * <code>repeated .io.dmcapps.proto.catalog.Product products = 1;</code>
   */
  io.dmcapps.proto.catalog.ProductOrBuilder getProductsOrBuilder(
      int index);
}
